spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8000

logging:
  file:
    name: logs/demoappjava.log
    path: demoappjava
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























